// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABntTAi9jhJ2gDZ4xPYyFXehZxTKC8Avg',
    appId: '1:748107057461:web:ae43bcde876c9a2023247c',
    messagingSenderId: '748107057461',
    projectId: 'florencehomes-95f02',
    authDomain: 'florencehomes-95f02.firebaseapp.com',
    storageBucket: 'florencehomes-95f02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD20PxrcC_2mZFSTZoeDDfmv06JgSKxMrg',
    appId: '1:748107057461:android:964ad752b467511723247c',
    messagingSenderId: '748107057461',
    projectId: 'florencehomes-95f02',
    storageBucket: 'florencehomes-95f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk1U-9ECRgQdIi_GDdX7dfr-Zpyorizxk',
    appId: '1:748107057461:ios:deac99393a70c76a23247c',
    messagingSenderId: '748107057461',
    projectId: 'florencehomes-95f02',
    storageBucket: 'florencehomes-95f02.firebasestorage.app',
    iosBundleId: 'com.florence.homes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk1U-9ECRgQdIi_GDdX7dfr-Zpyorizxk',
    appId: '1:748107057461:ios:a8d1cfea982a105623247c',
    messagingSenderId: '748107057461',
    projectId: 'florencehomes-95f02',
    storageBucket: 'florencehomes-95f02.firebasestorage.app',
    iosBundleId: 'com.example.florenceHomes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABntTAi9jhJ2gDZ4xPYyFXehZxTKC8Avg',
    appId: '1:748107057461:web:7732ad3606008def23247c',
    messagingSenderId: '748107057461',
    projectId: 'florencehomes-95f02',
    authDomain: 'florencehomes-95f02.firebaseapp.com',
    storageBucket: 'florencehomes-95f02.firebasestorage.app',
  );
}
