// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDidjmizHdbsNh3KUKpxODfTEmcLH93GuA',
    appId: '1:540264056673:web:1420910872d6e8d3bc2720',
    messagingSenderId: '540264056673',
    projectId: 'florencehomes-12a57',
    authDomain: 'florencehomes-12a57.firebaseapp.com',
    databaseURL: 'https://florencehomes-12a57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'florencehomes-12a57.firebasestorage.app',
    measurementId: 'G-78WTF0C50R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7JRxtEp6mlPAh_4fA5ExzZRPD2U0Jk4k',
    appId: '1:540264056673:android:6b66f5f3fdb5cad7bc2720',
    messagingSenderId: '540264056673',
    projectId: 'florencehomes-12a57',
    databaseURL: 'https://florencehomes-12a57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'florencehomes-12a57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGQ5r1QvkL-U1kVrpTW1amLzNmBu6zLQ',
    appId: '1:540264056673:ios:78ad13cf67abb808bc2720',
    messagingSenderId: '540264056673',
    projectId: 'florencehomes-12a57',
    databaseURL: 'https://florencehomes-12a57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'florencehomes-12a57.firebasestorage.app',
    iosBundleId: 'com.florence.homes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZGQ5r1QvkL-U1kVrpTW1amLzNmBu6zLQ',
    appId: '1:540264056673:ios:d942ca2f16946371bc2720',
    messagingSenderId: '540264056673',
    projectId: 'florencehomes-12a57',
    databaseURL: 'https://florencehomes-12a57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'florencehomes-12a57.firebasestorage.app',
    iosBundleId: 'com.example.florenceHomes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDidjmizHdbsNh3KUKpxODfTEmcLH93GuA',
    appId: '1:540264056673:web:dcc3d55fa58d2511bc2720',
    messagingSenderId: '540264056673',
    projectId: 'florencehomes-12a57',
    authDomain: 'florencehomes-12a57.firebaseapp.com',
    databaseURL: 'https://florencehomes-12a57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'florencehomes-12a57.firebasestorage.app',
    measurementId: 'G-TKD70SYDD5',
  );

}